name: 'Deploy workflow'
on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: 'Build and test'
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and test with Maven
        run: mvn --batch-mode --update-snapshots verify
  deploy:
    name: 'Deploy the application'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config committer.name "GitHub Actions"
          git config committer.email noreply@github.com
          git config author.name ${{ github.actor }}
          git config author.email ${{ github.actor }}@users.noreply.github.com
      - name: Set up release version number 
        run: |
            versionNumber=$(mvn -B help:evaluate -Dexpression=project.version 2> /dev/null | grep -v '\[.*' | sed -e "s/-SNAPSHOT$//")
            export VERSION_NUMBER=$versionNumber
            echo "::set-env name=VERSION_NUMBER::$VERSION_NUMBER"
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ env.VERSION_NUMBER }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Deploy on GitHub Packages
        run: mvn -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
