name: 'Release workflow'
on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Release the application'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build the release application
        run: mvn --batch-mode package
      - run: mkdir release && cp target/*.jar release
      - uses: actions/upload-artifact@v2
        with:
          name: Calculator-release
          path: release

  post_release:
    name: 'Create a release on GitHub'
    needs: release

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com
      - name: Get the release version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Extract release notes
        id: extract_release_notes
        uses: ffurrer2/extract-release-notes@v1
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.extract_release_notes.outputs.release_notes }}
          draft: false
          prerelease: false
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: Calculator-release
      - name: Upload Release Asset
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Calculator-release.zip
          asset_name: Calculator-${{ steps.get_version.outputs.VERSION }}.zip
          asset_content_type: application/zip
